#!/bin/busybox sh

echo "Init running basic"


/bin/busybox mount -t proc none /proc
/bin/busybox mount -t sysfs none /sys
/bin/busybox --install -s /bin
/bin/hostname -F /etc/hostname
/bin/mdev -s
/bin/busybox mount -t devpts none /dev/pts
ifup lo
ifup eth0
chown -R root:root /root
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys
/bin/dropbear -R -p 22
exec /bin/busybox sh
