keys:
  - &gregor age19jzcaspvpg3k8ay27ncx88wp6a3hn0perxc8q2cqfxela9nhgstsklmp82
  - &neil age1ynrxqlq47e9ctd5d4gv59rvlp7j78gy6yctg30d4wvpv6wl4nc8svjjaht
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *gregor
        - *neil
