keys:
  - &users:
    - &neil age1ynrxqlq47e9ctd5d4gv59rvlp7j78gy6yctg30d4wvpv6wl4nc8svjjaht
  - &hosts:
    - &pi400 age1q3ty8xy4n6mnr5p8vdrt7737q8rgmy4gltmp84d4aawtwyyzl9ksjtdz9z
  - &recovery:
    - &recovery_key age1zlllg9jenfywwzar00cd7l82tvnazlj7p06ugdjmwhgghxvts30q3pdzzp
creation_rules:
  - path_regex: hosts/pi400/secrets.(ya?ml|json)$
    key_groups:
    - age:
      - *recovery_key
      - *pi400
      - *neil
  - path_regex: hosts/yellow/secrets.(ya?ml|json)$
    key_groups:
    - age:
      - *recovery_key
      - *neil
  - path_regex: hosts/common/secrets.(ya?ml|json)$
    key_groups:
    - age:
      - *recovery_key
      - *pi400
      - *neil
  - path_regex: home/neil/secrets.(ya?ml|json)$
    key_groups:
    - age:
      - *recovery_key
      - *neil
