#!/bin/sh
#
# Start the dropbear ssh server

case "$1" in 
start)
  printf "Starting ssh server"
  /bin/dropbear -R -p 22
  [ $? = 0 ] && echo "OK" || echo "FAIL"
  ;;
stop)
  printf "Stopping ssh server"
  [ $? = 0 ] && echo "OK" || echo "FAIL"
  ;;
restart|reload)
  "$0" stop
  "$0" start
  ;;
*)
  echo "Usage $0 {start|stop|restart|reload}"
  exit 1
esac

exit $?
